%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%        Creanted by Yun Wu                %
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
clear;
clc;
close all;

para;
for sensor_height = 3:7

    for sensor_pitch_angle = 4:8

        %% Figure Setting 
        figure('position', [0, 0, 2048, 384]);
        figaxe = axes;
        hold on;
        grid on;
        axis([ -3*distance/2-5 3*distance/2+5 ...
            0 pole_height]);
        xticks(-100:2:100)
        yticks(-100:2:100)
        title(strcat('Black Poles and Lidar Beams (Red Beam -> Pitch Angle: ', ...
                num2str(-sensor_pitch_angle),' degrees)', ...
                ', Height: ', num2str(sensor_height), ...
                ', Vehicle Height: ', num2str(carheight), ...
                ', Vehicle Length: ', num2str(carlength), ...
                ', Human Height: ', num2str(peopleheight), ...
                ', Unit: m'))

        %% Pole Plot
        poleplot(figaxe, distance/2, pole_height)
        poleplot(figaxe, -distance/2, pole_height)
        poleplot(figaxe, 3*distance/2, pole_height)
        poleplot(figaxe, -3*distance/2, pole_height)

        %% Lidar Plot
        lidarplot(figaxe, -5*distance/2-5:0.01:999,  5*distance/2, -1, ...
                    sensor_pitch_angle, angle_up, angle_step, angle_down, ...
                    sensor_height)
        lidarplot(figaxe, -3*distance/2-5:0.01:999,  3*distance/2, -1, ...
                    sensor_pitch_angle, angle_up, angle_step, angle_down, ...
                    sensor_height)        
        lidarplot(figaxe, -distance/2-5:0.01:999,  distance/2, -1, ... 
                    sensor_pitch_angle, angle_up, angle_step, angle_down, ...
                    sensor_height)
        lidarplot(figaxe, distance/2-5:0.01:999,  -distance/2, -1, ... 
                    sensor_pitch_angle, angle_up, angle_step, angle_down, ...
                    sensor_height)  
        lidarplot(figaxe, 3*distance/2-5:0.01:999,  -3*distance/2, -1, ...
                    sensor_pitch_angle, angle_up, angle_step, angle_down, ...
                    sensor_height)   

        lidarplot(figaxe, -999:0.01:-3*distance/2+5,  3*distance/2, 1, ...
                    sensor_pitch_angle, angle_up, angle_step, angle_down, ...
                    sensor_height)    
        lidarplot(figaxe, -999:0.01:-distance/2+5,  distance/2, 1, ... 
                    sensor_pitch_angle, angle_up, angle_step, angle_down, ...
                    sensor_height)     
        lidarplot(figaxe, -999:0.01:distance/2+5,  -distance/2, 1, ...
                    sensor_pitch_angle, angle_up, angle_step, angle_down, ...
                    sensor_height) 
        lidarplot(figaxe, -999:0.01:3*distance/2+5,  -3*distance/2, 1, ...
                    sensor_pitch_angle, angle_up, angle_step, angle_down, ...
                    sensor_height)
        lidarplot(figaxe, -999:0.01:5*distance/2+5,  -5*distance/2, 1, ...
                    sensor_pitch_angle, angle_up, angle_step, angle_down, ...
                    sensor_height) 


        % Car Plot
        carplot(figaxe, distance/2, carheight, carlength)
        carplot(figaxe, 3*distance/4, carheight, carlength)
        carplot(figaxe, distance, carheight, carlength)
        carplot(figaxe, 1.4*distance, carheight, carlength)

        % People Plot
        peopleplot(figaxe, -distance/2-1, peopleheight)
        peopleplot(figaxe, -3*distance/4-1, peopleheight)
        peopleplot(figaxe, -distance-1, peopleheight)
        peopleplot(figaxe, -1.4*distance-1, peopleheight)

        %% dummy
        dummy = 1;
        savefig(strcat('figs/Height', num2str(sensor_height), ...
                    'Pitch', num2str(-sensor_pitch_angle), ...
                    '.fig'));
        close all;
    
    end
    
end